### ISSUE TITLE
ccm-datastore: using http is blocked but https not responding

### ISSUE THREAD

**Issue by MoritzKemp** [akless/ccm-market#1]
There is an issue for the demo-part of the components.
When components, like the bugtracker, using the remote ccm-store at 
_ccm2.inf.h-brs.de/index.js_ using **http** its blocked
for unsecure connections (which is generally a good idea).

But switching to **https** doesnt help because there seems to be no
service for https connections to ccm2.inf.h-brs.de/index.js. Doesnt get 
any response.
![ccm-issue](https://cloud.githubusercontent.com/assets/4232890/18225516/ea141f94-71f3-11e6-9136-c3cebd71d3af.png)

Note that this is an issue inside the context of the market.
Using unsecure connections to ccm2.inf.h-brs.de/index.js e.g.
from home works fine.

**Comment by akless** [comment]
Thank's for report. If you call the market place with https then all other resources must use https too. In other case it throws an unsecure error. The sandbox server ccm2.inf.h-brs.de don't support https because it's only a sandbox server without security. If you call the market place with http all works fine.

**Comment by MoritzKemp** [comment]
Oh, I totaly forgot about this https/http rule. Didn't mention it because i always used the link given by the github.io page which changed to secure couple of days ago. Thank you!
